### ISSUE TITLE
Error 1101 Worker threw exception

### ISSUE THREAD

**Issue by Cinorid** [3Kmfi6HP/EDtunnel#155]
Hi
I'm on latest commit 9feb7585a050a513e0c7290ca3d85765e2b64c98 and still receiving '1101 Worker threw exception' error.
thanks

**Comment by waited33** [comment]
[https://github.com/waited33/new/blob/master/QQ%E6%88%AA%E5%9B%BE20240427214527.png?raw=true](url)

**Comment by waited33** [comment]
[https://raw.githubusercontent.com/waited33/new/master/QQ%E6%88%AA%E5%9B%BE20240427214527.png?token=GHSAT0AAAAAACJZ226CGLJKDGAH5OHRXLW4ZRNAOSQ](url)

**Comment by waited33** [comment]
Error 1101

**Comment by simple003** [comment]
我也是一样的问题

**Comment by Cinorid** [comment]
Solved in issue #158

**Comment by Cinorid** [comment]
https://www.qfchat.free.hr/2024/05/cloudflare-workers-vless-1011.html
