### ISSUE TITLE
ERROR 1101

### ISSUE THREAD

**Issue by crystavine** [3Kmfi6HP/EDtunnel#156]
Plis Update.

**Comment by Decadefraiz** [comment]
我也是同样的问题，不管是用workers部署还是用pages部署，都显示ERROR1101，希望大佬修复一下代码，感激不尽！！

**Comment by JustLagom** [comment]
> 我也是同样的问题，不管是用workers部署还是用pages部署，都显示ERROR1101，希望大佬修复一下代码，感激不尽！！

vlessconfig内输出了vless：//特征值被cf追杀了

**Comment by Decadefraiz** [comment]
> > 我也是同样的问题，不管是用workers部署还是用pages部署，都显示ERROR1101，希望大佬修复一下代码，感激不尽！！
> 
> vlessconfig内输出了vless：//特征值被cf追杀了

大佬，具体是那一段啊，有修复办法吗？

**Comment by JustLagom** [comment]
> > > 我也是同样的问题，不管是用workers部署还是用pages部署，都显示ERROR1101，希望大佬修复一下代码，感激不尽！！
> > 
> > 
> > vlessconfig内输出了vless：//特征值被cf追杀了
> 
> 大佬，具体是那一段啊，有修复办法吗？

我项目里做了修改了，不再输出配置而是通过订阅器返回链接信息，规避字段检测

**Comment by wdde** [comment]
please update the worker.js in code, its update state is still 2 weeks ago.

**Comment by NameUndefined** [comment]
> > > > 我也是同样的问题，不管是用workers部署还是用pages部署，都显示ERROR1101，希望大佬修复一下代码，感激不尽！！
> > > 
> > > 
> > > vlessconfig内输出了vless：//特征值被cf追杀了
> > 
> > 
> > 大佬，具体是那一段啊，有修复办法吗？
> 
> 我项目里做了修改了，不再输出配置而是通过订阅器返回链接信息，规避字段检测

将代码里的所有 "vless://" 替换为 "bbb://" 就行了，在clash里导入时再手动换成"vless://"

**Comment by Mysteryexe** [comment]
> > > > > I have the same problem. Regardless of whether I deploy with workers or pages, ERROR1101 is displayed. I hope you can fix the code. Thank you very much! !
> > > > 
> > > > 
> > > > vlessconfig outputs vless://characteristic value being chased by cf
> > > 
> > > 
> > > Boss, which section is it specifically? Is there any way to fix it?
> > 
> > 
> > I have made changes in my project. I no longer output the configuration but return the link information through the subscriber to avoid field detection.
> 
> Just replace all "vless://" in the code with "bbb://", and then manually replace it with "vless://" when importing in clash

it doesnt work for me, still 1101

**Comment by JustLagom** [comment]
> > > > > > I have the same problem. Regardless of whether I deploy with workers or pages, ERROR1101 is displayed. I hope you can fix the code. Thank you very much! !
> > > > > 
> > > > > 
> > > > > vlessconfig outputs vless://characteristic value being chased by cf
> > > > 
> > > > 
> > > > Boss, which section is it specifically? Is there any way to fix it?
> > > 
> > > 
> > > I have made changes in my project. I no longer output the configuration but return the link information through the subscriber to avoid field detection.
> > 
> > 
> > Just replace all "vless://" in the code with "bbb://", and then manually replace it with "vless://" when importing in clash
> 
> it doesnt work for me, still 1101

你必须删除原来的旧项目，重新创建一个
You have to delete the original old project and recreate a new one

**Comment by JustLagom** [comment]
> > > > > > > > I have the same problem. Regardless of whether I deploy with workers or pages, ERROR1101 is displayed. I hope you can fix the code. Thank you very much! !
> > > > > > > 
> > > > > > > 
> > > > > > > vlessconfig outputs vless://characteristic value being chased by cf
> > > > > > 
> > > > > > 
> > > > > > Boss, which section is it specifically? Is there any way to fix it?
> > > > > 
> > > > > 
> > > > > I have made changes in my project. I no longer output the configuration but return the link information through the subscriber to avoid field detection.
> > > > 
> > > > 
> > > > Just replace all "vless://" in the code with "bbb://", and then manually replace it with "vless://" when importing in clash
> > > 
> > > 
> > > it doesnt work for me, still 1101
> > 
> > 
> > You have to delete the original old project and recreate a new one
> 
> ty for your reply! i tried and its not giving 1101 anymore but in clash it gives error 522 for the profile

我不太清楚522错误是什么，不知道你使用了什么代码
I'm not quite sure what the 522 error is and what code you used

**Comment by Mysteryexe** [comment]
> > > > > > > > > I have the same problem. Regardless of whether I deploy with workers or pages, ERROR1101 is displayed. I hope you can fix the code. Thank you very much! !
> > > > > > > > 
> > > > > > > > 
> > > > > > > > vlessconfig outputs vless://characteristic value being chased by cf
> > > > > > > 
> > > > > > > 
> > > > > > > Boss, which section is it specifically? Is there any way to fix it?
> > > > > > 
> > > > > > 
> > > > > > I have made changes in my project. I no longer output the configuration but return the link information through the subscriber to avoid field detection.
> > > > > 
> > > > > 
> > > > > Just replace all "vless://" in the code with "bbb://", and then manually replace it with "vless://" when importing in clash
> > > > 
> > > > 
> > > > it doesnt work for me, still 1101
> > > 
> > > 
> > > You have to delete the original old project and recreate a new one
> > 
> > 
> > ty for your reply! i tried and its not giving 1101 anymore but in clash it gives error 522 for the profile
> 
> 我不太清楚522错误是什么，不知道你使用了什么代码 I'm not quite sure what the 522 error is and what code you used

ahh i fixed the problem it was something with subconverter
rn it shows configs in the profile but none works
i dont know if its bc my internet or nah

**Comment by liming123qq** [comment]
现在又不行了

**Comment by Mysteryexe** [comment]
> > > > > > > > > I have the same problem. Regardless of whether I deploy with workers or pages, ERROR1101 is displayed. I hope you can fix the code. Thank you very much! !
> > > > > > > > 
> > > > > > > > 
> > > > > > > > vlessconfig outputs vless://characteristic value being chased by cf
> > > > > > > 
> > > > > > > 
> > > > > > > Boss, which section is it specifically? Is there any way to fix it?
> > > > > > 
> > > > > > 
> > > > > > I have made changes in my project. I no longer output the configuration but return the link information through the subscriber to avoid field detection.
> > > > > 
> > > > > 
> > > > > Just replace all "vless://" in the code with "bbb://", and then manually replace it with "vless://" when importing in clash
> > > > 
> > > > 
> > > > it doesnt work for me, still 1101
> > > 
> > > 
> > > You have to delete the original old project and recreate a new one
> > 
> > 
> > ty for your reply! i tried and its not giving 1101 anymore but in clash it gives error 522 for the profile
> 
> 我不太清楚522错误是什么，不知道你使用了什么代码 I'm not quite sure what the 522 error is and what code you used

Oh my god, i fixed all problems and mannn! [your version of edgetunnel](https://github.com/JustLagom/EDGETUNNEL) works PERFECT, ping is 200 and the ip is usa
It loads cf websites too!
thanks alooot

**Comment by qfluck** [comment]
参考这个 https://www.qfchat.free.hr/2024/05/cloudflare-workers-vless-1011.html
