### ISSUE TITLE
userID[uuid]不能随便修改么

### ISSUE THREAD

**Issue by xiaolong-chen** [3Kmfi6HP/EDtunnel#83]
如题，用 https://1024tools.com/uuid 生成的uuid，替换 _worker.js 里的uuid，搭建后，获取订阅地址的网页无法访问
https://xxx.workers.dev/uuid

保持脚本默认的uuid，就可以

**Comment by wyl2000** [comment]
用v2ray生成vless的UUID试试，这样是没问题的

**Comment by xiaolong-chen** [comment]
> 用v2ray生成vless的UUID试试，这样是没问题的

呃。。。现在（https://1024tools.com/uuid ）生成的又可以用了，那天试了好几个都不行
