### ISSUE TITLE
这代码有点意思

### ISSUE THREAD

**Issue by ymyuuu** [3Kmfi6HP/EDtunnel#98]
<img width="1123" alt="image" src="https://github.com/3Kmfi6HP/EDtunnel/assets/135582157/b5b715e9-f8cf-417f-a55a-f1232ee03372">
我不理解

**Comment by manhuaxian** [comment]
我刚才搜了一下，脚本里已经找不到这个字眼了，但是脚本最后一次修改是2天前，你的提问，我这里看到是19小时前，会不会是别人的脚本里的。但是，赶紧别用那个脚本了，那个屁股歪了。

**Comment by ymyuuu** [comment]
> 我擦，我也看到了，还真是！啥情况，大佬屁股歪了还是不小心的！

这谁敢用,卧槽

**Comment by manhuaxian** [comment]
> > 我擦，我也看到了，还真是！啥情况，大佬屁股歪了还是不小心的！
> 
> 这有点高级

我刚才去看了一下我之前用他的脚本的，bestip用的地址是别的地址。不管是那种情况，还是希望大佬还是早点改掉吧。玩技术就单纯的玩技术。

**Comment by ymyuuu** [comment]
> > > 我擦，我也看到了，还真是！啥情况，大佬屁股歪了还是不小心的！
> > 
> > 
> > 这有点高级
> 
> 我刚才去看了一下我之前用他的脚本的，bestip用的地址是别的地址。不管是那种情况，还是希望大佬还是早点改掉吧。玩技术就单纯的玩技术。

有点怕怕
